import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot training and validation metrics."
    )
    parser.add_argument(
        "--log_file",
        required=True,
        help="Training log CSV generated by src/train.py.",
    )
    parser.add_argument(
        "--output_dir",
        default="./outputs/plots",
        help="Directory for generated plots.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    log_file = Path(args.log_file)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    log_df = pd.read_csv(log_file)

    required_columns = {
        "epoch",
        "train_loss",
        "train_accuracy",
        "valid_loss",
        "valid_accuracy",
    }

    missing_columns = required_columns - set(log_df.columns)

    if missing_columns:
        raise ValueError(
            f"Missing columns in training log: {sorted(missing_columns)}"
        )

    epochs = log_df["epoch"]

    plt.figure(figsize=(8, 5))
    plt.plot(
        epochs,
        log_df["train_loss"],
        marker="o",
        label="Train Loss",
    )
    plt.plot(
        epochs,
        log_df["valid_loss"],
        marker="o",
        label="Validation Loss",
    )
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training and Validation Loss")
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        output_dir / "loss_curve.png",
        dpi=300,
    )
    plt.close()

    plt.figure(figsize=(8, 5))
    plt.plot(
        epochs,
        log_df["train_accuracy"],
        marker="o",
        label="Train Accuracy",
    )
    plt.plot(
        epochs,
        log_df["valid_accuracy"],
        marker="o",
        label="Validation Accuracy",
    )
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy (%)")
    plt.title("Training and Validation Accuracy")
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        output_dir / "accuracy_curve.png",
        dpi=300,
    )
    plt.close()

    print(f"Training plots saved to: {output_dir}")


if __name__ == "__main__":
    main()